services:
  app:
    build: .
    environment:
      PORT: 8000
      DRIVER: "mysql"
      ADDRESS: "service/mysql"
      DB_PORT: 3306
      USERNAME: "root"
      PASSWORD: "test1234"
      NAME: "alta"
    restart: always
    ports:
      - 8081:8000
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080